input_dir: ${PROJECT_DIR}/Modules/Design/Sources/Design
output_dir: ${PROJECT_DIR}/Modules/Design/Sources/Design

xcassets:
  inputs:
    - Icons.xcassets
    - Colors.xcassets
  outputs:
    - templateName: swift5
      params:
        publicAccess: true
      output: Assets.swift

fonts:
  inputs:
    - Fonts
  outputs:
    - templateName: swift5
      params:
        publicAccess: true
      output: Fonts.swift
